version: 2

project_name: bbox

builds:
  - id: bbox
    main: ./cmd/bbox
    binary: bbox
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - arm64

archives:
  - id: bbox-bundle
    ids:
      - bbox
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    files:
      - none*

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

release:
  prerelease: auto
