#!/bin/sh
set -eu

usage() {
	echo "usage: $0 [--verify]" >&2
	exit 2
}

verify=0
if [ "${1:-}" = "--verify" ]; then
	verify=1
	shift
fi

if [ "$#" -ne 0 ]; then
	usage
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
source_file="$repo_root/cmd/bbox-seccomp-launcher/main.c"
out_dir="$repo_root/internal/embeddedlauncher"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM

build_launcher() {
	goos="$1"
	goarch="$2"
	cc="$3"
	out="$4"

	if [ "$goos" != "linux" ]; then
		echo "unsupported goos: $goos" >&2
		exit 1
	fi

	"$cc" -O2 -o "$out" "$source_file"
}

emit_generated_file() {
	goarch="$1"
	binary="$2"
	target="$3"
	real_var="$4"
	other_var="$5"

	{
		echo "// Code generated by scripts/generate-embedded-launchers.sh; DO NOT EDIT."
		echo
		echo "package embeddedlauncher"
		echo
		printf "var %s = []byte{\n" "$real_var"

		count=0
		for b in $(LC_ALL=C od -An -v -t x1 "$binary"); do
			if [ $((count % 12)) -eq 0 ]; then
				printf "\t"
			fi
			printf "0x%s," "$b"
			count=$((count + 1))
			if [ $((count % 12)) -eq 0 ]; then
				printf "\n"
			else
				printf " "
			fi
		done
		if [ $((count % 12)) -ne 0 ]; then
			printf "\n"
		fi
		echo "}"
		echo
		printf "var %s = []byte{}\n" "$other_var"
	} >"$target"
}

amd64_bin="$tmpdir/bbox-seccomp-launcher-linux-amd64"
arm64_bin="$tmpdir/bbox-seccomp-launcher-linux-arm64"

amd64_cc="${CC:-cc}"
arm64_cc="${AARCH64_CC:-aarch64-linux-gnu-gcc}"

build_launcher linux amd64 "$amd64_cc" "$amd64_bin"
build_launcher linux arm64 "$arm64_cc" "$arm64_bin"

generated_amd64="$tmpdir/generated_linux_amd64.go"
generated_arm64="$tmpdir/generated_linux_arm64.go"

emit_generated_file amd64 "$amd64_bin" "$generated_amd64" launcherLinuxAMD64 launcherLinuxARM64
emit_generated_file arm64 "$arm64_bin" "$generated_arm64" launcherLinuxARM64 launcherLinuxAMD64

gofmt -w "$generated_amd64" "$generated_arm64"

if [ "$verify" -eq 1 ]; then
	if ! cmp -s "$generated_amd64" "$out_dir/generated_linux_amd64.go"; then
		echo "internal/embeddedlauncher/generated_linux_amd64.go is out of date" >&2
		exit 1
	fi
	if ! cmp -s "$generated_arm64" "$out_dir/generated_linux_arm64.go"; then
		echo "internal/embeddedlauncher/generated_linux_arm64.go is out of date" >&2
		exit 1
	fi
	exit 0
fi

cp "$generated_amd64" "$out_dir/generated_linux_amd64.go"
cp "$generated_arm64" "$out_dir/generated_linux_arm64.go"
