#!/bin/sh
set -eu

usage() {
	echo "usage: $0 [--verify]" >&2
	exit 2
}

verify=0
if [ "${1:-}" = "--verify" ]; then
	verify=1
	shift
fi

if [ "$#" -ne 0 ]; then
	usage
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/.." && pwd)
source_file="$repo_root/cmd/bbox-seccomp-launcher/main.c"
out_dir="$repo_root/internal/embeddedlauncher"
generator_script="$repo_root/scripts/generate-embedded-launchers.sh"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT INT TERM

build_launcher() {
	goos="$1"
	goarch="$2"
	cc="$3"
	out="$4"

	if [ "$goos" != "linux" ]; then
		echo "unsupported goos: $goos" >&2
		exit 1
	fi

	"$cc" -O2 -o "$out" "$source_file"
}

sha256_file() {
	sha256sum "$1" | awk '{print $1}'
}

emit_payload_var() {
	binary="$1"
	var_name="$2"

	printf "var %s = []byte{\n" "$var_name"

	count=0
	for b in $(LC_ALL=C od -An -v -t x1 "$binary"); do
		if [ $((count % 12)) -eq 0 ]; then
			printf "\t"
		fi
		printf "0x%s," "$b"
		count=$((count + 1))
		if [ $((count % 12)) -eq 0 ]; then
			printf "\n"
		else
			printf " "
		fi
	done
	if [ $((count % 12)) -ne 0 ]; then
		printf "\n"
	fi
	echo "}"
}

emit_generated_file() {
	target="$1"
	amd64_binary="$2"
	arm64_binary="$3"
	source_hash="$4"
	script_hash="$5"

	{
		echo "// Code generated by scripts/generate-embedded-launchers.sh; DO NOT EDIT."
		echo "// Launcher source SHA256: $source_hash"
		echo "// Generator script SHA256: $script_hash"
		echo
		echo "package embeddedlauncher"
		echo
		# Each target-specific file must compile on its own, so it carries both
		# payloads even though the Go toolchain only includes one file per GOARCH.
		emit_payload_var "$amd64_binary" launcherLinuxAMD64
		echo
		emit_payload_var "$arm64_binary" launcherLinuxARM64
	} >"$target"
}

amd64_bin="$tmpdir/bbox-seccomp-launcher-linux-amd64"
arm64_bin="$tmpdir/bbox-seccomp-launcher-linux-arm64"
source_hash=$(sha256_file "$source_file")
script_hash=$(sha256_file "$generator_script")

amd64_cc="${CC:-cc}"
arm64_cc="${AARCH64_CC:-aarch64-linux-gnu-gcc}"

build_launcher linux amd64 "$amd64_cc" "$amd64_bin"
build_launcher linux arm64 "$arm64_cc" "$arm64_bin"

generated_amd64="$tmpdir/generated_linux_amd64.go"
generated_arm64="$tmpdir/generated_linux_arm64.go"

emit_generated_file "$generated_amd64" "$amd64_bin" "$arm64_bin" "$source_hash" "$script_hash"
emit_generated_file "$generated_arm64" "$amd64_bin" "$arm64_bin" "$source_hash" "$script_hash"

gofmt -w "$generated_amd64" "$generated_arm64"

if [ "$verify" -eq 1 ]; then
	if ! grep -Fq "// Launcher source SHA256: $source_hash" "$out_dir/generated_linux_amd64.go"; then
		echo "internal/embeddedlauncher/generated_linux_amd64.go is out of date" >&2
		exit 1
	fi
	if ! grep -Fq "// Generator script SHA256: $script_hash" "$out_dir/generated_linux_amd64.go"; then
		echo "internal/embeddedlauncher/generated_linux_amd64.go is out of date" >&2
		exit 1
	fi
	if ! grep -Fq "// Launcher source SHA256: $source_hash" "$out_dir/generated_linux_arm64.go"; then
		echo "internal/embeddedlauncher/generated_linux_arm64.go is out of date" >&2
		exit 1
	fi
	if ! grep -Fq "// Generator script SHA256: $script_hash" "$out_dir/generated_linux_arm64.go"; then
		echo "internal/embeddedlauncher/generated_linux_arm64.go is out of date" >&2
		exit 1
	fi
	exit 0
fi

cp "$generated_amd64" "$out_dir/generated_linux_amd64.go"
cp "$generated_arm64" "$out_dir/generated_linux_arm64.go"
